# Generated by Django 2.0.5 on 2018-05-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='usuario_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='questao',
            name='questao_objetiva',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='questao_pergunta',
            field=models.CharField(max_length=100),
        ),
    ]
